### ISSUE TITLE
It doesn't work with any not trivial RAML

### ISSUE THREAD

**Issue by pbochynski** [mulesoft-labs/osprey-mock-service#12]
I tried with several examples and it always crashes (usually on JSON schema parsing). You can check it on RAML tutorial. Checkout RAML https://github.com/raml-org/raml-tutorial-200 and try to mock it.

```
osprey-mock-service -f jukebox-api.raml -p 8000
Error: Unable to compile JSON schema for post /artists: schema with key or id "http://jsonschema.net" already exists
    at checkUnique (/usr/local/lib/node_modules/osprey-mock-service/node_modules/osprey/node_modules/osprey-method-handler/node_modules/ajv/lib/ajv.js:316:13)
    at _addSchema (/usr/local/lib/node_modules/osprey-mock-service/node_modules/osprey/node_modules/osprey-method-handler/node_modules/ajv/lib/ajv.js:203:13)
    at Ajv.compile (/usr/local/lib/node_modules/osprey-mock-service/node_modules/osprey/node_modules/osprey-method-handler/node_modules/ajv/lib/ajv.js:94:21)
    at jsonBodyValidationHandler (/usr/local/lib/node_modules/osprey-mock-service/node_modules/osprey/node_modules/osprey-method-handler/osprey-method-handler.js:375:20)
    at jsonBodyHandler (/usr/local/lib/node_modules/osprey-mock-service/node_modules/osprey/node_modules/osprey-method-handler/osprey-method-handler.js:347:21)
    at /usr/local/lib/node_modules/osprey-mock-service/node_modules/osprey/node_modules/osprey-method-handler/osprey-method-handler.js:293:29
    at Array.forEach (native)
    at /usr/local/lib/node_modules/osprey-mock-service/node_modules/osprey/node_modules/osprey-method-handler/osprey-method-handler.js:289:14
    at Array.forEach (native)
    at bodyHandler (/usr/local/lib/node_modules/osprey-mock-service/node_modules/osprey/node_modules/osprey-method-handler/osprey-method-handler.js:277:9)

```

**Comment by blakeembrey** [comment]
Hi @pbochynski! This is actually coming from the JSON schema validator and is caused by the incorrect `id` set on the schemas in the tutorial. This is because every schema in the tutorial incorrectly has the same `id`. It probably shouldn't be an error though, so I'm going to open an issue in AJV for this discussion.

**Comment by blakeembrey** [comment]
Opened a PR on the tutorial to fix this issue too: https://github.com/raml-org/raml-tutorial-200/pull/2.

**Comment by gkimpson** [comment]
I am getting the same error when trying to run the following command on the same raml tutorial.

```
osprey -f jukebox-api.raml -p 3000 -a localhost:8080
```

Do I need to make any other adjustments?

**Comment by blakeembrey** [comment]
@gkimpson It appears to be fine for me using both `osprey` and `osprey-mock-service`. Are you using the latest changes in `master`?

**Comment by gkimpson** [comment]
@blakeembrey I'll have to give this another go and double check i'm using the latest changes thanks
