### ISSUE TITLE
RAML 1.0 support - date-only type causes "No method in multimethod"

### ISSUE THREAD

**Issue by nomiarnoid** [mulesoft-labs/osprey-mock-service#27]
Hello,

I encounter the following error when using the "date-only" type for an object property :
`
Error: No method in multimethod 'datatype-expansion.canonical-form/lt' for dispatch value: ["date-only" "date-only"]
    at Object.cljs$core$throw_no_method_error [as throw_no_method_error] (/usr/local/nvm/versions/node/v6.9.1/lib/node_modules/osprey-mock-service/node_modules/datatype-expansion/node/cljs/core.js:33311:8)
    at G__10851__3 (/usr/local/nvm/versions/node/v6.9.1/lib/node_modules/osprey-mock-service/node_modules/datatype-expansion/node/cljs/core.js:33369:11)
    at G__10851 [as call] (/usr/local/nvm/versions/node/v6.9.1/lib/node_modules/osprey-mock-service/node_modules/datatype-expansion/node/cljs/core.js:33628:20)
    at /usr/local/nvm/versions/node/v6.9.1/lib/node_modules/osprey-mock-service/node_modules/datatype-expansion/node/datatype_expansion/canonical_form.js:778:45
    at /usr/local/nvm/versions/node/v6.9.1/lib/node_modules/osprey-mock-service/node_modules/datatype-expansion/node/cljs/core.js:19036:96
    at /usr/local/nvm/versions/node/v6.9.1/lib/node_modules/osprey-mock-service/node_modules/datatype-expansion/node/cljs/core.js:19037:3
    at cljs.core.PersistentVector.cljs$core$IReduce$_reduce$arity$3 (/usr/local/nvm/versions/node/v6.9.1/lib/node_modules/osprey-mock-service/node_modules/datatype-expansion/node/cljs/core.js:19052:3)
    at Function.cljs.core.reduce.cljs$core$IFn$_invoke$arity$3 (/usr/local/nvm/versions/node/v6.9.1/lib/node_modules/osprey-mock-service/node_modules/datatype-expansion/node/cljs/core.js:7733:13) 
    at cljs$core$reduce (/usr/local/nvm/versions/node/v6.9.1/lib/node_modules/osprey-mock-service/node_modules/datatype-expansion/node/cljs/core.js:7701:25)
    at /usr/local/nvm/versions/node/v6.9.1/lib/node_modules/osprey-mock-service/node_modules/datatype-expansion/node/datatype_expansion/canonical_form.js:776:146
`

You can find attached a simple .raml file which reproduces the error.

Please forgive me if I am doing something wrong or if this issue is a duplicate. I am still a noob with RAML :-(

Thank you very much !

[api.raml.txt](https://github.com/mulesoft-labs/osprey-mock-service/files/682876/api.raml.txt)

**Comment by jstoiko** [comment]
@nomiarnoid: I was able to reproduce using the RAML attached. 

Bumped the version of `datatype-expansion` in [Osprey](https://github.com/mulesoft/osprey/pull/116/commits/1f3ae122671a57447ac9746a3ecd0a0232fc2e6b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R51) and the error disappeared. You can simply reinstall `osprey-mock-service#raml1.0` + dependencies and it should work.

**Comment by nomiarnoid** [comment]
Yes, it works, thank you very much !
